services:
    App\Command\TokenRefreshCommand:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@app.hubspot.hubspot_manager'
        tags:
            - { name: 'console.command', command: 'app:token:refresh' }

    App\Command\BeanstalkQueueFetcherCommand:
        arguments:
            - '@leezy.pheanstalk.primary'
            - '@doctrine.orm.default_entity_manager'
            - '@app.hubspot.hubspot_manager'
            - '%app.tube.hubspot-fetch%'
        tags:
            - { name: 'console.command', command: 'app:beanstalk:queue-hubspot-fetcher' }

    App\Command\BeanstalkQueueFetcherEnqueueCommand:
        arguments:
            - '@leezy.pheanstalk.primary'
            - '%app.tube.hubspot-fetch%'
        tags:
            - { name: 'console.command', command: 'app:beanstalk:queue-fetcher-enqueue' }

    App\Command\CronHubspotGatherCommand:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@leezy.pheanstalk.primary'
            - '%app.tube.hubspot-fetch%'
            - '@app.hubspot.hubspot_manager'
            - '@app.wicked_reports.wicked_report_manager'
        tags:
            - { name: 'console.command', command: 'app:cron:hubspot-gather' }
