services:
    App\Controller\Api\TokenApiController:
        arguments:
            - '@app.hubspot.hubspot_manager'
            - '@form.factory'
            - '@app.queue.hubspot_token_queue'
        public: true
