version: "3"

services:
    "hubspot-db":
        image: mysql:5.7
        container_name: "hubspot-db"
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wickedreport-hubspot-db
            MYSQL_USER: wickedreport-hubspot-u
            MYSQL_PASSWORD: 3478u6r3ir
        ports:
            - 43306:3306
            - 43060:33060

    "hubspot-beanstalkd":
        image: bodsch/docker-beanstalkd
        container_name: "hubspot-beanstalkd"

    php-api:
        build:
            context: .docker/php7-fpm
            args:
                TIMEZONE: UTC
        container_name: "hubspot-php-api"
        volumes:
            - ./backend/:/var/www/symfony/
            - ./bin/install-php:/var/www/symfony/install-php
        depends_on:
            - "hubspot-db"
            - "hubspot-beanstalkd"
        ports:
            - 9000:9000

    "hubspot-nginx":
        build: ".docker/nginx"
        container_name: "hubspot-nginx"
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - ./backend/:/var/www/symfony/
            - ./frontend/:/var/www/frontend/
            - ./bin/install-yarn:/var/www/frontend/install-yarn
        depends_on:
            - php-api
