version: "3"

services:
    db:
        image: mysql:5.7
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wickedreport-hubspot-db
            MYSQL_USER: wickedreport-hubspot-u
            MYSQL_PASSWORD: 3478u6r3ir
        ports:
            - 43306:3306
            - 43060:33060

    "hubspot-beanstalkd":
        image: bodsch/docker-beanstalkd
        container_name: "hubspot-beanstalkd"

    php-api:
        build:
            context: .docker/php7-fpm
            args:
                TIMEZONE: UTC
        container_name: "hubspot-php-api"
        volumes:
            - ./backend/:/var/www/symfony/
        depends_on:
            - db
            - beanstalkd
        ports:
            - 9000:9000

    "backend-hubspot.wr.loc":
        build: ".docker/backend-hubspot.wr.loc"
        container_name: "backend-hubspot.wr.loc"
        ports:
            - 11080:11080
        volumes:
            - ./backend/:/var/www/symfony/
        depends_on:
            - php-api

    "frontend-hubspot.wr.loc":
        build: ".docker/frontend-hubspot.wr.loc"
        container_name: "frontend-hubspot.wr.loc"
        ports:
            - 12080:12080
        volumes:
            - ./frontend/:/var/www/frontend/

    proxy:
        build: .docker/proxy
        container_name: "hubspot.wr.loc"
        ports:
            - 80:80
        depends_on:
          - "frontend-hubspot.wr.loc"
          - "backend-hubspot.wr.loc"
