parameters:
    app.beanstalkd.host: '%env(BEANSTALKD_HOST)%'
    app.beanstalkd.port: '%env(BEANSTALKD_PORT)%'

leezy_pheanstalk:
    pheanstalks:
        primary:
            server: '%app.beanstalkd.host%'
            port: '%app.beanstalkd.port%'
            default: true
