export const ACTION_TOKEN_CHANGE_CODE = 'ACTION_TOKEN_CHANGE_CODE';
export const ACTION_TOKEN_CHANGE_TOKEN = 'ACTION_TOKEN_CHANGE_TOKEN';
export const ACTION_TOKEN_CHANGE_CODE_TOKEN = 'ACTION_TOKEN_CHANGE_CODE_TOKEN';
