monolog:
    channels: ['hubspot-api']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]

        hubspot-api:
            type:  rotating_file
            path:  '%kernel.logs_dir%/hubspot-api-%kernel.environment%.log'
            level: debug
            channels: ["hubspot-api"]
            max_files: 10

        wicked-reports-api:
            type:  rotating_file
            path:  '%kernel.logs_dir%/wicked-reports-api-%kernel.environment%.log'
            level: debug
            channels: ["wicked-reports-api"]
            max_files: 10
